FROM docker.io/library/debian:trixie as sandbox-core
WORKDIR app
#section-start install essential ssh stuff
RUN apt-get update && apt-get -y install \
   ssh \
   sshfs
#section-end
#section-start make dev account
RUN useradd -m dev
RUN chsh -s /bin/bash dev
#section-end
#section-start make volume mounts
RUN mkdir /home/dev/.pi
RUN chown dev:dev /home/dev/.pi
RUN mkdir /home/dev/workspace
RUN chown dev:dev /home/dev/workspace
#section-end
#section-start get ssh working perfectly!
RUN groupadd -g 995 sshd
RUN usermod -g 995 sshd
COPY ./files/container_startup_script.sh /app/container_startup_script.sh
COPY ./files/sshd_config /etc/ssh/sshd_config
EXPOSE 22
CMD ["/bin/bash", "/app/container_startup_script.sh"]
#section-end
FROM sandbox-core
WORKDIR app
#section-start install locales
# These have something to do with how the system displays things
RUN apt-get update && \
    apt-get install -y locales && \
    sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen && \
    rm -rf /var/lib/apt/lists/*
#section-end
#section-start install system essentials (stuff needed for installing stuff)
RUN apt-get update && apt-get -y install \
   curl \
   git \
   sudo \
   xz-utils
#section-end
#section-start install languages
#section-start install python
RUN apt-get update && apt-get -y install \
   python3
#section-end
#section-start install nodejs
RUN echo a && curl -L -o /app/node.tar.xz https://nodejs.org/dist/v24.18.0/node-v24.18.0-linux-x64.tar.xz
RUN tar -xf /app/node.tar.xz -C /app
RUN mv /app/node-v24.18.0-linux-x64 /app/node
RUN echo "export PATH=/app/node/bin:$PATH" >> /etc/bash.bashrc
ENV PATH="/app/node/bin:${PATH}"
#section-end
#section-end
#section-start install pi agent
RUN npm install -g --ignore-scripts @earendil-works/pi-coding-agent
RUN apt-get update && apt-get install -y \
   fd-find \
   ripgrep
#section-end
#section-start install neovim (and plugin supporting stuff)
RUN apt-get update && apt-get -y install \
   neovim \
   fzf \
   tmux \
   xclip
#section-end
#section-start install document programs
RUN apt-get update && apt-get -y install \
   pandoc \
   texlive-latex-recommended
#section-end
RUN echo "export EDITOR=\"nvim\"" >> /etc/bash.bashrc
#section-start install nvim configuration
ARG NVIM_GIT_COMMIT="81e4becd5e897e07fdb68ebe0d279803623fc855"
RUN sudo -u dev mkdir -p /home/dev/.config/nvim
RUN sudo -u dev git clone https://github.com/arkrp/vimrc.git /home/dev/.config/nvim
RUN cd /home/dev/.config/nvim/ && sudo -u dev git remote set-url origin git@github.com:arkrp/vimrc.git
RUN cd /home/dev/.config/nvim/ && sudo -u dev git checkout ${NVIM_GIT_COMMIT}
RUN sudo -u dev nvim +q #this is needed to make the plugins work
RUN sudo -u dev nvim +PlugInstall +qa #install the nvim plugins
#section-end
