FROM docker.io/library/debian:trixie
WORKDIR app
#section-start install essential ssh stuff
RUN apt-get update && apt-get -y install \
   ssh \
   sshfs
#section-end
#section-start install other applications!
RUN apt-get update && apt-get -y install \
   pandoc \
   texlive-latex-recommended
#section-end
#section-start make dev account
RUN useradd -m dev
RUN chsh -s /bin/bash dev
#section-end
#section-start get ssh working perfectly!
RUN groupadd -g 995 sshd
RUN usermod -g 995 sshd
RUN mkdir /home/dev/workspace
RUN chown dev:dev /home/dev/workspace
COPY ./files/container_startup_script.sh /app/container_startup_script.sh
COPY ./files/sshd_config /etc/ssh/sshd_config
EXPOSE 22
CMD ["/bin/bash", "/app/container_startup_script.sh"]
#section-end
