FROM docker.io/library/debian:trixie-slim
WORKDIR app
RUN apt-get update && apt-get -y install \
   ssh \
   sshfs
RUN useradd -m dev
RUN useradd -m sandbox
RUN groupadd -g 995 sshd
RUN usermod -g 995 sshd
COPY ./files/container_startup_script.sh /app/container_startup_script.sh
COPY ./files/sshd_config /etc/ssh/sshd_config
EXPOSE 22
CMD ["/bin/bash", "/app/container_startup_script.sh"]
