#section-start core layer
# This is the inner core, contains the functionality necessary for the ssh connection and not much else
FROM docker.io/library/debian:trixie as dev-core
WORKDIR app
#section-start install ssh and sshfs
RUN apt-get update && apt-get -y install \
   ssh \
   sshfs
#section-end
#section-start make user
RUN useradd -m dev
RUN chsh -s /bin/bash dev
#section-end
#section-start make the workspace mount point
RUN mkdir /home/dev/workspace
RUN chown dev:dev /home/dev/workspace
#section-end
#section-start configure ssh stuff for launch
RUN groupadd -g 995 sshd
RUN usermod -g 995 sshd
COPY ./files/sshd_config /etc/ssh/sshd_config
COPY ./files/container_startup_script.sh /app/container_startup_script.sh
COPY ./files/non_core_startup_script.sh /app/non_core_startup_script.sh
EXPOSE 22
CMD ["/bin/bash", "/app/container_startup_script.sh"]
#section-end
#section-end
#section-start installation layer
FROM dev-core as dev-installed
# This layer has the programs installed but not configured
WORKDIR app
#section-start install applications
#section-start install absolute essentials
#section-start install stuff from apt
RUN apt-get update && apt-get -y install \
   sudo \
   tmux \
   git \
   curl \
   build-essential
#section-end
#section-start install neovim
RUN curl -o /app/nvim.tar.gz -L https://github.com/neovim/neovim/releases/download/v0.12.5/nvim-linux-x86_64.tar.gz
RUN tar --strip-components=1 -xzf /app/nvim.tar.gz -C /usr
#section-end
#section-start install the sandbox scripts!
COPY ./files/sandbox.sh /app/sandbox.sh
#section-end
#section-end
#section-start install helpful extras
#section-start install stuff from apt
RUN apt-get update && apt-get -y install \
   man \
   fzf \
   zathura \
   xclip \
   feh
#section-end
#section-start install the readmd script!
COPY ./files/readmd.sh /app/readmd.sh
#section-end
#section-end
#section-start install locales
# These have something to do with how the system displays things
RUN apt-get update && \
    apt-get install -y locales && \
    sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen && \
    rm -rf /var/lib/apt/lists/*
#section-end
#section-end
#section-end
#section-start configuration layer
#this layer configured the programs for use
FROM dev-installed
WORKDIR app
#section-start give the dev user sudo
RUN usermod -a -G sudo dev
#section-start give the user a password so they can use sudo
RUN echo "dev:palp" | chpasswd
#section-end
#section-end
#section-start make the dev_scripts mount point
RUN mkdir /home/dev/dev_scripts
RUN chown dev:dev /home/dev/dev_scripts
#section-end
#section-start load bash configuration
COPY ./files/bash.bashrc /etc/bash.bashrc
#section-end
#section-start configure tmux
COPY files/tmux.conf /home/dev/.tmux.conf
#section-end
#section-start install nvim configuration
ARG NVIM_GIT_COMMIT="42d0d1708aead5df85e2cb0a60be85a1af47f041"
RUN sudo -u dev mkdir -p /home/dev/.config/nvim
RUN sudo -u dev git clone https://github.com/arkrp/vimrc.git /home/dev/.config/nvim
RUN cd /home/dev/.config/nvim/ && sudo -u dev git remote set-url origin git@github.com:arkrp/vimrc.git
RUN cd /home/dev/.config/nvim/ && sudo -u dev git checkout ${NVIM_GIT_COMMIT}
RUN sudo -u dev nvim +q #this is needed to make the plugins work
RUN sudo -u dev nvim +PlugInstall +qa #install the nvim plugins
#section-end
#section-end
